name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x # Use a current LTS version

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest # Or specify a pnpm version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Use --frozen-lockfile in CI if a lockfile is committed

      - name: Build
        run: pnpm build # This should output to 'dist' by default

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
